export const CHANGE_RESISTANCE_1 = 'CHANGE_RESISTANCE_1';
export const CHANGE_RESISTANCE_2 = 'CHANGE_RESISTANCE_2';
export const CHANGE_VOLTAGE_T = 'CHANGE_VOLTAGE_T';

export const CHANGE_USER_CURRENT_1 = 'CHANGE_USER_CURRENT_1';
export const CHANGE_USER_CURRENT_2 = 'CHANGE_USER_CURRENT_2';
export const CHANGE_USER_CURRENT_T = 'CHANGE_USER_CURRENT_T';

export const CHANGE_USER_VOLTAGE_1 = 'CHANGE_USER_VOLTAGE_1';
export const CHANGE_USER_VOLTAGE_2 = 'CHANGE_USER_VOLTAGE_2';

export const CHANGE_USER_RESISTANCE_T = 'CHANGE_USER_RESISTANCE_T';

export const CHANGE_R_T_LABEL = 'CHANGE_R_T_LABEL';

export const CHANGE_V_1_LABEL = 'CHANGE_V_1_LABEL';
export const CHANGE_V_2_LABEL = 'CHANGE_V_2_LABEL';

export const CHANGE_I_1_LABEL = 'CHANGE_I_1_LABEL';
export const CHANGE_I_2_LABEL = 'CHANGE_I_2_LABEL';
export const CHANGE_I_T_LABEL = 'CHANGE_I_T_LABEL';
